apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod
  labels:  
    appname: myapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
